services:
  server:
    container_name: server
    build: ./server # Location of the Dockerfile for the client
    restart: always
    environment:
      MONGO_ADDR: mongo # hostname of the mongo container
      MONGO_DB: prod
      WAIT_HOSTS: mongo:27017 # wait for mongo to start up before starting the server
    depends_on:
      - mongo
    networks:
      - java-server-network
      - mongo-network
    ports:
      - "80:4567"
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_DB: prod
    networks:
      - mongo-network
    volumes:
        - mongo_data:/data/db
        - ./database:/docker-entrypoint-initdb.d

networks:
  java-server-network:
  mongo-network:

volumes:
  mongo_data:
