name: "Update Angular"
on: # when the action should run. Can also be a CRON or in response to external events. see https://git.io/JeBz1
  schedule:
    - cron:  '0 12 * * 1'

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'UMM-CSci-3601'
    steps:
      - name: Updating ng dependencies # the magic happens here!
        uses: tinesoft/ngx-uptodate@v1.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          project-path: ./client/
          pr-branch-prefix: ng-update-
          pr-title: 'Update Angular dependencies'
          pr-labels: dependencies, javascript
